### ISSUE TITLE
E-commerce tracking with Google Analytics

### ISSUE THREAD

**Issue by mglobel** [jeffreybiles/simpler-ember-sparks-website#15]
Hola sir @jeffreybiles! Got a bit caught up this week getting the apartment setup, but about to tackle this. 
## Task
- [ ] add ecommerce tracking snippet to conversion page
- [ ] provide details on how to view conversion information, campaigns, and other GA basics around ecommerce tracking

Estimated time: 2 hrs

**Comment by jeffreybiles** [comment]
Congrats on getting the apartment set up!
