### ISSUE TITLE
Add paypal btn to checkout

### ISSUE THREAD

**Issue by mglobel** [jeffreybiles/simpler-ember-sparks-website#18]
Starting work on this for this week.

**Comment by jeffreybiles** [comment]
Awesome.  Looking forward to it.

**Comment by mglobel** [comment]
@jeffreybiles Do you have a paypal business account? Currently using mine for development testing, but obvi shall need a real one for production. If not, let's make one! Since we'll be adding paypal alongside our existing credit card fields, I'd use this page to sign-up*: https://www.paypal.com/webapps/mpp/express-checkout

*They have like 5 different sign-up processes for their business accounts, but they all go the same place ultimately. It's just marketing gimmicks. But at some point it might ask you to make a cpl choices, here's the answers.
1) Paypal Premier vs Paypal Business
- choose paypal business, no cost difference, but does allow you to give access to your account to 'employees' 

2) Paypal standard ($0/mo) or Paypal pro ($30/mo)
- choose the standard option, shall work fine with what we've got

**Comment by jeffreybiles** [comment]
I replied via email to this issue, since this is public :)  Thanks for
putting in the work for this feature!
